### ISSUE TITLE
XSLT Stylesheet issue#2: there is no class CreativeWork 

### ISSUE THREAD

**Issue by gerontakos** [mixterj/VRA-RDF-Project#11]
The xsl2rdf.xsl transform, in its third template (matching vc:work), outputs the assertion that every vra:vra/vra:work is, in the RDF, rdf:type = http://purl.org/vra/CreativeWork, but there is no such class. I believe the correct class is http://purl.org/vra/Work.

**Comment by mixterj** [comment]
Yep, that was a carry over mistake. We modified the Vocabulary but not the Stylesheet.

**Comment by mixterj** [comment]
Just made that fix to the stylesheet
