### ISSUE TITLE
XSLT Stylesheet issue#3: vra:containedIn

### ISSUE THREAD

**Issue by gerontakos** [mixterj/VRA-RDF-Project#12]
It looks like there is no vra:containedIn property in the ontology. In the XSLT, the template matching on vc:name (mode=vra:Place) outputs vra:containedIn. We’re not sure if another property took its place or if it was considered superfluous. We’ll send a question about that to the VRA listserv.

**Comment by mixterj** [comment]
This was a deprecated property that was not removed from the mapping stylesheet. It is now fixed.
